# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gltpromptcontainer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9f67a786ff074f5f8d3eed9e6f397af6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9108d1c5f7ed478cb93fccdd428c60e1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_9f67a786ff074f5f8d3eed9e6f397af6 }}/manifestinteractive/teleprompter:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gltpromptcontainer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_75780a89a64f49099495542939eb0bcf }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_9f67a786ff074f5f8d3eed9e6f397af6 }}/manifestinteractive/teleprompter:${{ github.sha }}'